// unchecked/hevirtualtable/VirtualList.svelte
<script lang="ts">
	import type { Snippet, SvelteComponent } from 'svelte';
	import { tick } from 'svelte';
	import VirtualListTable from './VirtualListTable.svelte';
	import * as hp from './jshelper';

	let executing = false;
	let waiting = false;

	let listElRef: Element;
	let listInnerRef: Element;

	let prevScroll: number;

	interface Props {
		items: Array<any>;
		disabled?: boolean;
		horizontal?: boolean;
		firstRender?: number;
		buffer?: number;
		itemKey?: 'index' | ((item: any, index: number) => any);
		itemSize?: (item: any, index: number) => number | null | undefined | void;
		table?: boolean;
		prepend?: Snippet;
		row: Snippet<[item: any, i: number]>;
		append?: Snippet;
	}

	let {
		items,
		disabled = false,
		horizontal = false,
		firstRender = 10,
		buffer = 100,
		itemKey = 'index',
		itemSize,
		table = false,
		prepend,
		row,
		append
	}: Props = $props();

	function onscroll() {
		const listEl = listElRef!;
		if (!listEl) {
			return;
		}
		const currentScroll = getScroll(listEl);
		if (prevScroll !== null && buffer - Math.abs(currentScroll - prevScroll) >= 10) {
			return;
		}
		prevScroll = currentScroll;
		update();
	}

	let start = $state(0);
	let end = firstRender - 1;
	const end2 = $derived(hp.notGreaterThan(end, (items?.length || 1) - 1));
	let avgSize = $state(0);
	const runtimeSizes: Array<number> = $derived((items || []).map(() => 0));
	const sizes: Array<number> = $derived.by(() => {
		return (items || []).map((item, index) => {
			if (runtimeSizes && runtimeSizes[index] != null) {
				return runtimeSizes[index];
			}
			let r = itemSize?.(item, index);
			if (r == null) {
				r = avgSize;
			}
			return r;
		});
	});
	const positions: Array<number> = $derived.by(() => {
		const p: number[] = [];
		sizes.reduce((a, b) => {
			p.push(a);
			return a + b;
		}, 0);
		return p;
	});
	const startSize = $derived(positions[start] ? positions[start] : 0);

	const totalSize = $derived(
		positions.length > 0 ? positions[positions.length - 1] + hp.arrayLast(sizes) : 0
	);

	const endSize = $derived(positions[end2] ? totalSize - positions[end2] - sizes[end2] : 0);

	const visibleItemsInfo = $derived.by(() => {
		if (!items || disabled) {
			return [];
		}
		const r: { item: (typeof items)[0]; index: number }[] = [];

		for (let index = start; index <= end2; index++) {
			const item = items[index];
			if (!item) {
				break;
			}
			r.push({ item, index });
		}
		return r;
	});

	const listStyle = $derived(!disabled ? "overflow:'auto'" : '');

	function listInnerStyle() {
		const r: { [key: string]: string } = {
			display: 'flex'
		};
		if (!disabled) {
			if (!horizontal) {
				Object.assign(r, {
					'margin-top': startSize + 'px',
					'margin-bottom': endSize + 'px'
				});
			} else {
				Object.assign(r, {
					'margin-left': startSize + 'px',
					'margin-right': endSize + 'px',
					width: totalSize - endSize - startSize + 'px'
				});
			}
		}
		r['flex-direction'] = !horizontal ? 'column' : 'row';
		if (table) {
			// @ts-ignore
			delete r.display;
			delete r['flex-direction'];
		}
		return hp.stylesDictToString(r);
	}

	$effect(() => {
		update();
		try {
			createResizeObserver();
		} catch (error) {
			console.log(error);
			// ResizeObserver fallback
			//tick();
			//update();
		}
	});

	async function update() {
		if (executing) {
			waiting = true;
			return;
		}
		if (!items || disabled) {
			return;
		}
		executing = true;
		const listEl = listElRef!;
		const listInner = listInnerRef;
		if (!listEl || !listInner) {
			return;
		}

		if (!avgSize) {
			avgSize = getAvgSize();
		}

		start = getStart();
		end = getEnd();

		await tick();

		// updateRuntimeSize
		let updated;
		let vi0 = 0;
		const runtimeSizesTemp: Record<number, number> = {};
		const children = !table ? listInner.children : listInner.querySelector('tbody')!.children;
		for (let i = 0; i < children.length; i++) {
			const el = children[i];
			const cssPosition = hp.css(el, 'position');
			if (cssPosition && ['absolute', 'fixed'].includes(cssPosition)) {
				continue;
			}
			const size = hp.css(el, 'display') !== 'none' ? getOuterSize(<HTMLElement>el) : 0;
			const vi = el.getAttribute('vt-index');
			const index = vi ? parseInt(vi) : start + vi0;
			runtimeSizesTemp[index] = (runtimeSizesTemp[index] || 0) + size;
			vi0++;
		}
		for (const indexS of Object.keys(runtimeSizesTemp)) {
			const index = parseInt(indexS);
			if (runtimeSizes[index] !== runtimeSizesTemp[index]) {
				runtimeSizes[index] = runtimeSizesTemp[index];
				updated = true;
			}
		}
		if (updated) {
			await tick();
		}
		// call wating task if existing
		executing = false;
		if (waiting) {
			waiting = false;
			update();
		}

		// functions
		function getStart() {
			const startPosition = getScroll(listEl) - getPaddingStart(listEl) - buffer;
			console.log('startPosition ' + startPosition);
			console.log(positions);
			const r = hp.binarySearch(positions, (mid) => mid - startPosition, {
				returnNearestIfNoHit: true
			})!;
			return r.index;
		}
		function getEnd() {
			const endPosition =
				getScroll(listEl) - getPaddingStart(listEl) + getClientSize(listEl) + buffer;
			console.log('endPosition ' + endPosition);
			console.log(positions);
			const r = hp.binarySearch(positions, (mid) => mid - endPosition, {
				returnNearestIfNoHit: true
			})!;
			return r.index;
		}
		function getAvgSize() {
			const maxSampleCount = 10;
			const sizeArr: number[] = [];
			const children = !table ? listInner.children : listInner.querySelector('tbody')!.children;
			for (let index = 0; index < children.length; index++) {
				const el = <HTMLElement>children[index];
				const style = getComputedStyle(el);
				if (['absolute', 'fixed'].includes(style.position)) {
					continue;
				}
				const outerSize = getOuterSize(el);
				sizeArr.push(outerSize);
				if (sizeArr.length >= maxSampleCount) {
					break;
				}
			}
			if (sizeArr.length === 0) {
				return 0;
			}
			return sizeArr.reduce((a, b) => a + b, 0) / sizeArr.length;
		}
	}

	function getClientSize(el: Element) {
		const style = getComputedStyle(el);
		let r = parseFloat(!horizontal ? style.height : style.width);
		if (style.boxSizing === 'border-box') {
			if (!horizontal) {
				r -= parseFloat(style.borderTopWidth) - parseFloat(style.borderBottomWidth);
			} else {
				r -= parseFloat(style.borderLeftWidth) - parseFloat(style.borderRightWidth);
			}
		}
		return r;
	}
	function getOuterSize(el: Element) {
		let r = getClientSize(el);
		const style = getComputedStyle(el);
		if (!horizontal) {
			r +=
				parseFloat(style.borderTopWidth) +
				parseFloat(style.borderBottomWidth) +
				parseFloat(style.marginTop) +
				parseFloat(style.marginBottom);
		} else {
			r +=
				parseFloat(style.borderLeftWidth) +
				parseFloat(style.borderRightWidth) +
				parseFloat(style.marginLeft) +
				parseFloat(style.marginRight);
		}
		r = Number.isNaN(r) ? 0 : r;
		return r;
	}
	function getScroll(el: Element) {
		return !horizontal ? el.scrollTop : el.scrollLeft;
	}
	function getPaddingStart(el: Element) {
		const style = getComputedStyle(el);
		return !horizontal ? parseFloat(style.paddingTop) : parseFloat(style.paddingLeft);
	}

	// whatch
	function createResizeObserver() {
		const listEl = listElRef!;
		const resizeObserver = new ResizeObserver((entries) => {
			for (let entry of entries) {
				if (hp.hasClass(entry.target, 'vtlist')) {
					// if tree is resized, update layout
					update();
					break;
				}
			}
		});
		resizeObserver.observe(listEl);
	}

	function getItemKey(item: any, index: number) {
		if (itemKey) {
			if (typeof itemKey === 'string' && itemKey === 'index') {
				return index;
			} else if (typeof itemKey === 'function') {
				return itemKey(item, index);
			}
		}
	}
</script>

<!-- svelte-ignore non_reactive_update -->
<div class="vtlist" bind:this={listElRef} style={listStyle} {onscroll}>
	<VirtualListTable
		class="vtlist-inner"
		bind:el={listInnerRef}
		style={listInnerStyle()}
		{prepend}
		{append}
		{table}
	>
		{#if disabled}
			{#each items as item, i}
				{@render row(item, i)}
			{/each}
		{:else}
			{#each visibleItemsInfo as item, i}
				{@render row(item.item, i)}
			{/each}
		{/if}
	</VirtualListTable>
</div>

// unchecked/he-vue/VirtualList.vue
<template>
	<div class="vtlist" ref="listElRef" :style="listStyle" @scroll.passive="onscroll">
		<VirtualListTable class="vtlist-inner" ref="listInnerRef" :style="listInnerStyle" :table="table">
			<template #prepend>
				<slot name="prepend"></slot>
			</template>
			<template v-if="disabled">
				<template v-for="(item, index) in items" :key="getItemKey(item, index)">
					<slot :item="item" :index="index" />
				</template>
			</template>
			<template v-else>
				<template v-for="{ item, index } in visibleItemsInfo" :key="getItemKey(item, index)">
					<slot :item="item" :index="index" />
				</template>
			</template>
			<template #append>
				<slot name="append"></slot>
			</template>
		</VirtualListTable>
	</div>
</template>

<script lang="ts">
import {
	ref,
	computed,
	onMounted,
	nextTick,
	PropType,
	defineComponent,
	isVue2,
	isVue3,
	reactive,
	watch
} from 'vue-demi';
import * as hp from 'helper-js';
import { Accumulate } from 'helper-js';
import VirtualListTable from './VirtualListTable.vue';

const cpt = defineComponent({
	components: { VirtualListTable },
	props: {
		items: Array as PropType<any[]>,
		disabled: Boolean,
		horizontal: Boolean,
		firstRender: { type: Number, default: 10 },
		buffer: { type: Number, default: 100 },
		itemKey: {
			type: [String, Function] as PropType<'index' | ((item: any, index: number) => any)>
		},
		itemSize: {
			type: Function as PropType<(item: any, index: number) => number | null | undefined | void>
		},
		table: Boolean
	},
	setup(props) {
		const start = ref(0);
		const end = ref(props.firstRender - 1);
		const end2 = computed(() => hp.notGreaterThan(end.value, (props.items?.length || 1) - 1));
		const avgSize = ref(0);
		const startSize = computed(() => (positions.value[start.value] ? getPosition(start.value) : 0));
		const totalSize = computed(() =>
			positions.value.length > 0 ? getPosition(positions.value.length - 1) + hp.arrayLast(sizes.value) : 0
		);
		const endSize = computed(() =>
			positions.value[end2.value] ? totalSize.value - getPosition(end2.value) - sizes.value[end2.value] : 0
		);
		const listStyle = computed(() => (!props.disabled ? { overflow: 'auto' } : {}));
		const listInnerStyle = computed(() => {
			const r = {
				display: 'flex'
			};
			if (!props.disabled) {
				if (!props.horizontal) {
					Object.assign(r, {
						'margin-top': startSize.value + 'px',
						'margin-bottom': endSize.value + 'px'
					});
				} else {
					Object.assign(r, {
						'margin-left': startSize.value + 'px',
						'margin-right': endSize.value + 'px',
						width: totalSize.value - endSize.value - startSize.value + 'px'
					});
				}
			}
			r['flex-direction'] = !props.horizontal ? 'column' : 'row';
			if (props.table) {
				// @ts-ignore
				delete r.display;
				delete r['flex-direction'];
			}
			return r;
		});

		const runtimeSizes = computed<(number | null)[]>(() =>
			reactive<(number | null)[]>((props.items || []).map(() => null))
		);
		const sizes = computed<number[]>(() =>
			(props.items || []).map((item, index) => {
				if (runtimeSizes[index] != null) {
					return runtimeSizes[index];
				}
				let r = props.itemSize?.(item, index);
				if (r === null) {
					r = avgSize.value;
				}
				return r;
			})
		);
		const positions = computed<number[]>(() => {
			const p: number[] = [];
			sizes.value.reduce((a, b) => {
				p.push(a);
				return a + b;
			}, 0);
			return p;
		});
		watch(() => props.items, update);
		const visibleItemsInfo = computed(() => {
			if (!props.items || props.disabled) {
				return;
			}
			const r: { item: (typeof props.items)[0]; index: number }[] = [];

			for (let index = start.value; index <= end2.value; index++) {
				const item = props.items[index];
				if (!item) {
					break;
				}
				r.push({ item, index });
			}
			return r;
		});
		const listElRef = ref<HTMLElement>();
		const listInnerRef = ref();
		onMounted(async () => {
			update();
			try {
				createResizeObserver();
			} catch (error) {
				// ResizeObserver fallback
				await nextTick();
				update();
			}
		});

		let prevScroll: number;
		function onscroll() {
			const listEl = listElRef.value!;
			if (!listEl) {
				return;
			}
			const currentScroll = getScroll(listEl);
			if (prevScroll != null && props.buffer - Math.abs(currentScroll - prevScroll) >= 10) {
				return;
			}
			prevScroll = currentScroll;
			update();
		}

		let executing = false;
		let waiting = false;
		async function update() {
			if (executing) {
				waiting = true;
				return;
			}
			if (!props.items || props.disabled) {
				return;
			}
			executing = true;
			const listEl = listElRef.value!;
			const listInner: HTMLElement = listInnerRef.value?.$el;
			if (!listEl || !listInner) {
				return;
			}

			if (!avgSize.value) {
				avgSize.value = getAvgSize();
			}
			start.value = getStart();
			end.value = getEnd();

			await nextTick();

			// updateRuntimeSize
			let updated;
			let vi0 = 0;
			const runtimeSizesTemp: Record<number, number> = {};
			const children = !props.table ? listInner.children : listInner.querySelector('tbody')!.children;
			for (let i = 0; i < children.length; i++) {
				const el = children[i];
				const cssPosition = hp.css(el, 'position');
				if (cssPosition && ['absolute', 'fixed'].includes(cssPosition)) {
					continue;
				}
				const size = hp.css(el, 'display') !== 'none' ? getOuterSize(<HTMLElement>el) : 0;
				const vi = el.getAttribute('vt-index');
				const index = vi ? parseInt(vi) : start.value + vi0;
				runtimeSizesTemp[index] = (runtimeSizesTemp[index] || 0) + size;
				vi0++;
			}
			for (const indexS of Object.keys(runtimeSizesTemp)) {
				const index = parseInt(indexS);
				if (runtimeSizes.value[index] !== runtimeSizesTemp[index]) {
					runtimeSizes.value[index] = runtimeSizesTemp[index];
					updated = true;
				}
			}
			if (updated) {
				await nextTick();
			}
			// call wating task if existing
			executing = false;
			if (waiting) {
				waiting = false;
				update();
			}

			// functions
			function getStart() {
				const startPosition = getScroll(listEl) - getPaddingStart(listEl) - props.buffer;
				const r = hp.binarySearch(positions.value, (mid) => mid - startPosition, {
					returnNearestIfNoHit: true
				})!;
				return r.index;
			}
			function getEnd() {
				const endPosition = getScroll(listEl) - getPaddingStart(listEl) + getClientSize(listEl) + props.buffer;

				const r = hp.binarySearch(positions.value, (mid) => mid - endPosition, {
					returnNearestIfNoHit: true
				})!;
				return r.index;
			}
			function getAvgSize() {
				const maxSampleCount = 10;
				const sizeArr: number[] = [];
				const children = !props.table ? listInner.children : listInner.querySelector('tbody')!.children;
				for (let index = 0; index < children.length; index++) {
					const el = <HTMLElement>children[index];
					const style = getComputedStyle(el);
					if (['absolute', 'fixed'].includes(style.position)) {
						continue;
					}
					const outerSize = getOuterSize(el);
					sizeArr.push(outerSize);
					if (sizeArr.length >= maxSampleCount) {
						break;
					}
				}
				if (sizeArr.length === 0) {
					return 0;
				}
				return sizeArr.reduce((a, b) => a + b, 0) / sizeArr.length;
			}
		}
		function getClientSize(el: HTMLElement) {
			const style = getComputedStyle(el);
			let r = parseFloat(!props.horizontal ? style.height : style.width);
			if (style.boxSizing === 'border-box') {
				if (!props.horizontal) {
					r = r - parseFloat(style.borderTopWidth) - parseFloat(style.borderBottomWidth);
				} else {
					r = r - parseFloat(style.borderLeftWidth) - parseFloat(style.borderRightWidth);
				}
			}
			return r;
		}
		function getOuterSize(el: HTMLElement) {
			let r = getClientSize(el);
			const style = getComputedStyle(el);
			if (!props.horizontal) {
				r +=
					parseFloat(style.borderTopWidth) +
					parseFloat(style.borderBottomWidth) +
					parseFloat(style.marginTop) +
					parseFloat(style.marginBottom);
			} else {
				r +=
					parseFloat(style.borderLeftWidth) +
					parseFloat(style.borderRightWidth) +
					parseFloat(style.marginLeft) +
					parseFloat(style.marginRight);
			}
			r = Number.isNaN(r) ? 0 : r;
			return r;
		}
		function getScroll(el: HTMLElement) {
			return !props.horizontal ? el.scrollTop : el.scrollLeft;
		}
		function getPaddingStart(el: HTMLElement) {
			const style = getComputedStyle(el);
			return !props.horizontal ? parseFloat(style.paddingTop) : parseFloat(style.paddingLeft);
		}
		// function getPaddingEnd(el: HTMLElement) {
		//   const style = getComputedStyle(el);
		//   return !props.horizontal
		//     ? parseFloat(style.paddingBottom)
		//     : parseFloat(style.paddingRight);
		// }
		function getPosition(index: number): number {
			return positions.value[index];
		}

		function createResizeObserver() {
			const listEl = listElRef.value!;
			const resizeObserver = new ResizeObserver((entries) => {
				for (let entry of entries) {
					if (hp.hasClass(entry.target, 'vtlist')) {
						update();
						break;
					}
				}
			});
			resizeObserver.observe(listEl);
		}

		function getItemKey(item: any, index: number) {
			if (props.itemKey) {
				if (typeof props.itemKey === 'string' && props.itemKey === 'index') {
					return index;
				} else if (typeof props.itemKey === 'function') {
					return props.itemKey(item, index);
				}
			}
		}

		return {
			listElRef,
			listInnerRef,
			onscroll,
			listStyle,
			listInnerStyle,
			visibleItemsInfo,
			getItemKey,
			update,
			sizes,
			positions,
			runtimeSizes
		};
	}
});
export default cpt;
export type VtlistType = InstanceType<typeof cpt>;
</script>

<style></style>
